"""
server/app.py
-------------
FastAPI application entry point for service_impact_env.

Wires the ServiceImpactEnvironment into the OpenEnv HTTP/WebSocket server
using the create_app factory from openenv-core.

The server exposes:
  GET  /health     → {"status": "healthy"}
  GET  /schema     → action + observation + state JSON schemas
  GET  /metadata   → environment name, description, version
  GET  /state      → current episode state (HTTP mode only)
  POST /reset      → start new episode (HTTP mode only)
  POST /step       → execute action (HTTP mode only)
  WS   /ws         → persistent WebSocket session (primary protocol)

Usage:
  uvicorn server.app:app --host 0.0.0.0 --port 8000 --reload
"""
from __future__ import annotations

# Dual-import: relative works when run from repo root (PYTHONPATH=src:envs),
#              bare imports work inside Docker (/app/env on PYTHONPATH).
try:
    from openenv.core.env_server.http_server import create_app
except ImportError:
    from openenv.core.env_server import create_app  # type: ignore

try:
    from ..models import ServiceImpactAction, ServiceImpactObservation
    from .service_impact_environment import ServiceImpactEnvironment
except ImportError:
    from models import ServiceImpactAction, ServiceImpactObservation  # type: ignore
    from server.service_impact_environment import ServiceImpactEnvironment  # type: ignore


# Pass the CLASS (not an instance) so the server creates one environment
# per WebSocket session — required for concurrent session isolation.
# SUPPORTS_CONCURRENT_SESSIONS=True is set on the class, so max_concurrent_envs > 1 is safe.
app = create_app(
    ServiceImpactEnvironment,
    ServiceImpactAction,
    ServiceImpactObservation,
    env_name="service_impact_env",
    max_concurrent_envs=4,
)

# ---------------------------------------------------------------------------
# Override generic openenv-core metadata with cascade-mind–specific docs.
# FastAPI renders full Markdown in Swagger UI / ReDoc.
# ---------------------------------------------------------------------------
app.title   = "cascade-mind — Service Impact Analysis"
app.version = "0.2.0"
app.description = """
**cascade-mind** simulates the decision-making environment of an SRE engineer responding
to a production incident. Given a deployment change in one microservice, an agent must
trace the blast radius and identify every downstream service that could be impacted —
working only from the same realistic, sometimes-noisy tool output that an on-call
engineer would have.

The environment is built on a seeded `networkx` dependency graph of 15 microservices
across three teams. All tool responses — incident alerts, service registry lookups,
runbooks, and monitoring snapshots — are generated by **Llama-3.1-8B-Instruct** to
reflect real SRE workflows, with configurable signal noise on harder difficulty levels.

---

## How an Episode Works

1. **Reset** — a scenario is generated: one service has changed, an incident alert fires.
2. **Investigate** — use the tools below to explore the service graph and gather evidence.
3. **Submit** — declare your list of affected services. The episode ends and a score is returned.

Scores are computed as $F_{\\beta=2}$ (recall-weighted) against the ground truth graph,
with a small penalty for each service incorrectly included. The full correct answer is
revealed in the response so agents can learn from mistakes.

Difficulty controls how much noise appears in registry responses:
`easy` → clean output · `medium` → one service added/removed · `hard` → two added/removed.

---

## Available Tools

| Tool | Type | What it returns |
|---|---|---|
| `query_dependents` | Registry | Services that directly call the queried service |
| `query_dependencies` | Registry | Services the queried service depends on |
| `query_runbook` | Intelligence | Internal runbook: ownership, SLOs, known failure modes |
| `query_changelog` | Intelligence | Recent PR/deployment changelog for the changed service |
| `query_monitoring` | Intelligence | Live monitoring snapshot: latency, error rate, dependencies |
| `submit_affected` | Terminal | Submit final answer — ends the episode |

Registry queries draw from a shared **query budget of 10**. Intelligence tools
(`runbook`, `changelog`, `monitoring`) are always available and do not affect the budget.
Submitting the same registry query twice applies a small score penalty.

---

## Connecting via WebSocket

The recommended way to run a full episode is over the **WebSocket at `/ws`**, which
maintains session state across all interactions.

```python
import asyncio, json, websockets

async def run():
    async with websockets.connect("wss://rajkamal2819-cascade-mind.hf.space/ws") as ws:

        # Start a new episode
        await ws.send(json.dumps({"type": "reset", "data": {"seed": 42}}))
        obs = json.loads(await ws.recv())
        print(obs["data"]["message"])          # → incident alert text

        # Read the changelog (no budget impact)
        await ws.send(json.dumps({
            "type": "step",
            "data": {"action_type": "query_changelog", "service_name": "catalog_service"}
        }))
        print(json.loads(await ws.recv())["data"]["message"])

        # Query which services depend on catalog_service
        await ws.send(json.dumps({
            "type": "step",
            "data": {"action_type": "query_dependents", "service_name": "catalog_service"}
        }))
        print(json.loads(await ws.recv())["data"]["message"])

        # Submit your answer
        await ws.send(json.dumps({
            "type": "step",
            "data": {
                "action_type": "submit_affected",
                "affected_services": ["api_gateway", "cart_service", "web_backend"]
            }
        }))
        result = json.loads(await ws.recv())
        print("Score:", result["data"]["reward"])   # → float in [0.0, 1.0]

asyncio.run(run())
```

HTTP endpoints (`/reset`, `/step`) are also available for single-turn use,
but they do not share state between separate requests.

---

## Python Client

```python
from cascade_mind import ServiceImpactEnv

async with ServiceImpactEnv(base_url="https://rajkamal2819-cascade-mind.hf.space") as env:
    obs, _ = await env.reset(seed=0)
    print(obs.message)   # incident alert

    obs, reward, done, _, _ = await env.step(
        {"action_type": "query_dependents", "service_name": "catalog_service"}
    )
    print(obs.message)   # registry output
```

---

## Configuration

| Variable | Default | Description |
|---|---|---|
| `HF_TOKEN` | *(required)* | HuggingFace token — used to call Llama-3.1-8B via Cerebras |
| `LLM_SIMULATOR_ENABLED` | `true` | Set to `false` to use deterministic template responses |
| `LLM_CACHE_PATH` | `/app/llm_sim_cache.json` | Pre-warmed response cache for faster startup |

---

## Resources

- [GitHub — rajkamal2819/cascade-mind](https://github.com/rajkamal2819/cascade-mind)
- [HuggingFace Space](https://huggingface.co/spaces/Rajkamal2819/cascade-mind)
- [OpenEnv framework](https://github.com/meta-pytorch/OpenEnv)
"""

app.openapi_tags = [
    {
        "name": "Environment Control",
        "description": "Start a new episode with `/reset`, then advance it step by step with `/step`. "
                       "For full episodes, prefer the **WebSocket at `/ws`** — HTTP endpoints are "
                       "stateless and do not share session context between calls.",
    },
    {
        "name": "State Management",
        "description": "Read the current episode state at any point: which service changed, "
                       "how many registry queries remain, which services have been explored, "
                       "and (after submission) the ground-truth affected set.",
    },
    {
        "name": "Environment Info",
        "description": "Metadata about the environment: name, version, supported difficulty levels, "
                       "and descriptions of all available action types.",
    },
    {
        "name": "Schema",
        "description": "JSON Schema definitions for `ServiceImpactAction`, "
                       "`ServiceImpactObservation`, and `ServiceImpactState` — useful for "
                       "building typed clients.",
    },
    {
        "name": "Health",
        "description": "Returns `{\"status\": \"healthy\"}` when the server is ready to accept connections.",
    },
]

# ---------------------------------------------------------------------------
# MCP (Model Context Protocol) endpoint — RFC 003 compliance
# Exposes the environment as a tool-callable MCP server.
# GET  /mcp        → tools manifest (list all available tools)
# POST /mcp        → JSON-RPC 2.0 dispatcher (tools/list, tools/call)
# ---------------------------------------------------------------------------
from fastapi import Request
from fastapi.responses import JSONResponse

_MCP_TOOLS = [
    {
        "name": "query_dependents",
        "description": "Find services that directly call/depend on a given service. Uses query budget.",
        "inputSchema": {
            "type": "object",
            "properties": {"service_name": {"type": "string", "description": "Service to query"}},
            "required": ["service_name"],
        },
    },
    {
        "name": "query_dependencies",
        "description": "Find services that a given service directly depends on. Uses query budget.",
        "inputSchema": {
            "type": "object",
            "properties": {"service_name": {"type": "string", "description": "Service to query"}},
            "required": ["service_name"],
        },
    },
    {
        "name": "query_runbook",
        "description": "Fetch internal Confluence-style runbook for a service. FREE — no budget cost.",
        "inputSchema": {
            "type": "object",
            "properties": {"service_name": {"type": "string"}},
            "required": ["service_name"],
        },
    },
    {
        "name": "query_changelog",
        "description": "Fetch PR/changelog for the changed service. FREE — no budget cost.",
        "inputSchema": {
            "type": "object",
            "properties": {"service_name": {"type": "string"}},
            "required": [],
        },
    },
    {
        "name": "query_monitoring",
        "description": "Fetch Datadog-style monitoring snapshot for a service. FREE — no budget cost.",
        "inputSchema": {
            "type": "object",
            "properties": {"service_name": {"type": "string"}},
            "required": ["service_name"],
        },
    },
    {
        "name": "submit_affected",
        "description": "Submit final list of affected services. Ends episode, returns F-beta score.",
        "inputSchema": {
            "type": "object",
            "properties": {
                "affected_services": {
                    "type": "array",
                    "items": {"type": "string"},
                    "description": "List of all affected service names",
                }
            },
            "required": ["affected_services"],
        },
    },
]


@app.get("/mcp")
async def mcp_manifest():
    """MCP tools manifest — lists all available environment tools."""
    return {
        "schema_version": "2024-11-05",
        "name": "service_impact_env",
        "version": "0.2.0",
        "description": (
            "Cross-service impact analysis environment. Agents identify downstream "
            "services affected by a microservice change using LLM-simulated SRE tool output."
        ),
        "tools": _MCP_TOOLS,
        "execution": "Use the WebSocket at /ws for stateful episode execution.",
    }


@app.post("/mcp")
async def mcp_rpc(request: Request):
    """JSON-RPC 2.0 endpoint for MCP protocol compliance.

    Supports:
      tools/list  → returns full tools manifest
      tools/call  → returns tool schema (actual execution via WebSocket)
    """
    try:
        body   = await request.json()
        method = body.get("method", "")
        req_id = body.get("id", 1)

        if method == "initialize":
            return JSONResponse({
                "jsonrpc": "2.0", "id": req_id,
                "result": {
                    "protocolVersion": "2024-11-05",
                    "capabilities": {"tools": {}},
                    "serverInfo": {"name": "service_impact_env", "version": "0.2.0"},
                },
            })

        if method == "tools/list":
            return JSONResponse({
                "jsonrpc": "2.0", "id": req_id,
                "result": {"tools": _MCP_TOOLS},
            })

        if method == "tools/call":
            tool_name = body.get("params", {}).get("name", "")
            tool = next((t for t in _MCP_TOOLS if t["name"] == tool_name), None)
            if tool is None:
                return JSONResponse({
                    "jsonrpc": "2.0", "id": req_id,
                    "error": {"code": -32601, "message": f"Tool not found: {tool_name}"},
                })
            return JSONResponse({
                "jsonrpc": "2.0", "id": req_id,
                "result": {
                    "content": [{
                        "type": "text",
                        "text": (
                            f"Tool '{tool_name}' is available. "
                            f"Execute via WebSocket at /ws using action_type='{tool_name}' "
                            f"(or 'submit' for submit_affected)."
                        ),
                    }]
                },
            })

        return JSONResponse({
            "jsonrpc": "2.0", "id": req_id,
            "error": {"code": -32601, "message": f"Method not found: {method}"},
        })

    except Exception as exc:
        return JSONResponse(
            {"jsonrpc": "2.0", "id": None, "error": {"code": -32700, "message": str(exc)}},
            status_code=400,
        )


def main() -> None:
    """Entry point for `uv run --project . server`."""
    import uvicorn
    uvicorn.run(app, host="0.0.0.0", port=8000, log_level="info")


if __name__ == "__main__":
    main()
