"""
server/app.py
-------------
FastAPI application entry point for service_impact_env.

Wires the ServiceImpactEnvironment into the OpenEnv HTTP/WebSocket server
using the create_app factory from openenv-core.

The server exposes:
  GET  /health     → {"status": "healthy"}
  GET  /schema     → action + observation + state JSON schemas
  GET  /metadata   → environment name, description, version
  GET  /state      → current episode state (HTTP mode only)
  POST /reset      → start new episode (HTTP mode only)
  POST /step       → execute action (HTTP mode only)
  WS   /ws         → persistent WebSocket session (primary protocol)

Usage:
  uvicorn server.app:app --host 0.0.0.0 --port 8000 --reload
"""
from __future__ import annotations

# Dual-import: relative works when run from repo root (PYTHONPATH=src:envs),
#              bare imports work inside Docker (/app/env on PYTHONPATH).
try:
    from openenv.core.env_server.http_server import create_app
except ImportError:
    from openenv.core.env_server import create_app  # type: ignore

try:
    from ..models import ServiceImpactAction, ServiceImpactObservation
    from .service_impact_environment import ServiceImpactEnvironment
except ImportError:
    from models import ServiceImpactAction, ServiceImpactObservation  # type: ignore
    from server.service_impact_environment import ServiceImpactEnvironment  # type: ignore


# ─── Patch openenv-core web_interface for cascade-mind branding ───────────────
# Must happen BEFORE create_app() is called so the web interface picks up changes.
try:
    import openenv.core.env_server.web_interface as _wi

    # 1. Strip YAML frontmatter (--- ... ---) before the README is shown in the
    #    Gradio accordion — the raw README.md starts with HF Space config that
    #    renders as ugly plain text when Gradio displays it as Markdown.
    _orig_load_readme = _wi._load_readme_from_filesystem

    def _patched_load_readme(env_name):  # type: ignore[override]
        content = _orig_load_readme(env_name)
        if content and content.startswith("---"):
            end = content.find("\n---\n", 4)
            if end != -1:
                content = content[end + 5:].lstrip("\n")
        return content

    _wi._load_readme_from_filesystem = _patched_load_readme  # type: ignore[assignment]

    # 2. Replace the generic OpenEnv docs link in the Quick Start accordion with
    #    the cascade-mind Swagger / ReDoc link.
    _wi.DEFAULT_QUICK_START_MARKDOWN = _wi.DEFAULT_QUICK_START_MARKDOWN.replace(
        "For more information, see the [OpenEnv documentation](https://meta-pytorch.org/OpenEnv/).",
        "For more information, see the **[cascade-mind API docs](https://rajkamal2819-cascade-mind.hf.space/docs)**.",
    )
except Exception:
    pass  # Never crash the server over a cosmetic patch
# ─────────────────────────────────────────────────────────────────────────────


# Pass the CLASS (not an instance) so the server creates one environment
# per WebSocket session — required for concurrent session isolation.
# SUPPORTS_CONCURRENT_SESSIONS=True is set on the class, so max_concurrent_envs > 1 is safe.
app = create_app(
    ServiceImpactEnvironment,
    ServiceImpactAction,
    ServiceImpactObservation,
    env_name="service_impact_env",
    max_concurrent_envs=4,
)

# ---------------------------------------------------------------------------
# Override generic openenv-core metadata with cascade-mind–specific docs.
# FastAPI renders full Markdown in Swagger UI / ReDoc.
# ---------------------------------------------------------------------------
app.title   = "cascade-mind — Service Impact Analysis"
app.version = "0.2.0"
app.description = """
**cascade-mind** simulates the decision-making environment of an SRE engineer responding
to a production incident. Given a deployment change in one microservice, an agent must
trace the blast radius and identify every downstream service that could be impacted —
working only from the same realistic, sometimes-noisy tool output that an on-call
engineer would have.

The environment is built on a seeded `networkx` dependency graph of 30 microservices
across three teams. All tool responses — incident alerts, service registry lookups,
runbooks, and monitoring snapshots — are generated by **Llama-3.1-8B-Instruct** to
reflect real SRE workflows, with configurable signal noise on harder difficulty levels.

---

## How an Episode Works

1. **Reset** — a scenario is generated: one service has changed, an incident alert fires.
2. **Investigate** — use the tools below to explore the service graph and gather evidence.
3. **Submit** — declare your list of affected services. The episode ends and a score is returned.

Scores are computed as $F_{\\beta=2}$ (recall-weighted) against the ground truth graph,
with a small penalty for each service incorrectly included. The full correct answer is
revealed in the response so agents can learn from mistakes.

Difficulty controls how much noise appears in registry responses:
`easy` → clean output · `medium` → one service added/removed · `hard` → two added/removed.

---

## Available Tools

| Tool | Type | What it returns |
|---|---|---|
| `query_dependents` | Registry | Services that directly call the queried service |
| `query_dependencies` | Registry | Services the queried service depends on |
| `query_runbook` | Intelligence | Internal runbook: ownership, SLOs, known failure modes |
| `query_changelog` | Intelligence | Recent PR/deployment changelog for the changed service |
| `query_monitoring` | Intelligence | Live monitoring snapshot: latency, error rate, dependencies |
| `submit` | Terminal | Submit final answer — ends the episode |

Registry queries draw from a shared **query budget of 10**. Intelligence tools
(`runbook`, `changelog`, `monitoring`) are always available and do not affect the budget.
Submitting the same registry query twice applies a small score penalty.

---

## Connecting via WebSocket

The recommended way to run a full episode is over the **WebSocket at `/ws`**, which
maintains session state across all interactions.

```python
import asyncio, json, websockets

async def run():
    async with websockets.connect("wss://rajkamal2819-cascade-mind.hf.space/ws") as ws:

        # Start a new episode
        await ws.send(json.dumps({"type": "reset", "data": {"seed": 42}}))
        obs = json.loads(await ws.recv())
        print(obs["data"]["message"])          # → incident alert text

        # Read the changelog (no budget impact)
        await ws.send(json.dumps({
            "type": "step",
            "data": {"action_type": "query_changelog", "service_name": "catalog_service"}
        }))
        print(json.loads(await ws.recv())["data"]["message"])

        # Query which services depend on catalog_service
        await ws.send(json.dumps({
            "type": "step",
            "data": {"action_type": "query_dependents", "service_name": "catalog_service"}
        }))
        print(json.loads(await ws.recv())["data"]["message"])

        # Submit your answer
        await ws.send(json.dumps({
            "type": "step",
            "data": {
                "action_type": "submit",
                "affected_services": ["api_gateway", "cart_service", "web_backend"]
            }
        }))
        result = json.loads(await ws.recv())
        print("Score:", result["data"]["reward"])   # → float in [0.0, 1.0]

asyncio.run(run())
```

HTTP endpoints (`/reset`, `/step`) are also available for single-turn use,
but they do not share state between separate requests.

---

## Python Client

```python
from cascade_mind import ServiceImpactEnv

async with ServiceImpactEnv(base_url="https://rajkamal2819-cascade-mind.hf.space") as env:
    obs, _ = await env.reset(seed=0)
    print(obs.message)   # incident alert

    obs, reward, done, _, _ = await env.step(
        {"action_type": "query_dependents", "service_name": "catalog_service"}
    )
    print(obs.message)   # registry output
```

---

## Configuration

| Variable | Default | Description |
|---|---|---|
| `HF_TOKEN` | *(required)* | HuggingFace token — used to call Llama-3.1-8B via Cerebras |
| `LLM_SIMULATOR_ENABLED` | `true` | Set to `false` to use deterministic template responses |
| `LLM_CACHE_PATH` | `/app/llm_sim_cache.json` | Pre-warmed response cache for faster startup |

---

## Resources

- [GitHub — rajkamal2819/cascade-mind](https://github.com/rajkamal2819/cascade-mind)
- [HuggingFace Space](https://huggingface.co/spaces/Rajkamal2819/cascade-mind)
- [OpenEnv framework](https://github.com/meta-pytorch/OpenEnv)
"""

app.openapi_tags = [
    {
        "name": "Environment Control",
        "description": "Start a new episode with `/reset`, then advance it step by step with `/step`. "
                       "For full episodes, prefer the **WebSocket at `/ws`** — HTTP endpoints are "
                       "stateless and do not share session context between calls.",
    },
    {
        "name": "State Management",
        "description": "Read the current episode state at any point: which service changed, "
                       "how many registry queries remain, which services have been explored, "
                       "and (after submission) the ground-truth affected set.",
    },
    {
        "name": "Environment Info",
        "description": "Metadata about the environment: name, version, supported difficulty levels, "
                       "and descriptions of all available action types.",
    },
    {
        "name": "Schema",
        "description": "JSON Schema definitions for `ServiceImpactAction`, "
                       "`ServiceImpactObservation`, and `ServiceImpactState` — useful for "
                       "building typed clients.",
    },
    {
        "name": "Health",
        "description": "Returns `{\"status\": \"healthy\"}` when the server is ready to accept connections.",
    },
]

# ---------------------------------------------------------------------------
# Ground-truth graph — must be registered before the Gradio catch-all mount
# ---------------------------------------------------------------------------
from fastapi.responses import JSONResponse, RedirectResponse, HTMLResponse

@app.get("/graph/ground-truth", include_in_schema=False)
async def ground_truth_graph(seed: int = 0, difficulty: str = "easy"):
    """Serve a standalone interactive vis.js page of the full ground-truth graph."""
    try:
        from .playground import build_ground_truth_html
    except ImportError:
        from server.playground import build_ground_truth_html  # type: ignore
    html = build_ground_truth_html(seed=seed, difficulty=difficulty)
    return HTMLResponse(content=html)

# ---------------------------------------------------------------------------
# Playground — custom Gradio 6 interactive UI at /
# ---------------------------------------------------------------------------
try:
    import gradio as gr
    try:
        from .playground import playground_blocks, PLAYGROUND_CSS, PLAYGROUND_THEME
    except ImportError:
        from server.playground import playground_blocks, PLAYGROUND_CSS, PLAYGROUND_THEME  # type: ignore
    app = gr.mount_gradio_app(
        app, playground_blocks, path="/",
        css=PLAYGROUND_CSS, theme=PLAYGROUND_THEME,
    )
except Exception as _pg_exc:
    import warnings as _w
    _w.warn(f"cascade-mind: playground mount failed -- {_pg_exc}", stacklevel=1)

# ---------------------------------------------------------------------------
# MCP (Model Context Protocol) endpoint — RFC 003 compliance
# Exposes the environment as a tool-callable MCP server.
# GET  /mcp        → tools manifest (list all available tools)
# POST /mcp        → JSON-RPC 2.0 dispatcher (tools/list, tools/call)
# ---------------------------------------------------------------------------
from fastapi import Request

_MCP_TOOLS = [
    {
        "name": "query_dependents",
        "description": "Find services that directly call/depend on a given service. Uses query budget.",
        "inputSchema": {
            "type": "object",
            "properties": {"service_name": {"type": "string", "description": "Service to query"}},
            "required": ["service_name"],
        },
    },
    {
        "name": "query_dependencies",
        "description": "Find services that a given service directly depends on. Uses query budget.",
        "inputSchema": {
            "type": "object",
            "properties": {"service_name": {"type": "string", "description": "Service to query"}},
            "required": ["service_name"],
        },
    },
    {
        "name": "query_runbook",
        "description": "Fetch the internal runbook for a service: ownership, SLOs, and known failure modes.",
        "inputSchema": {
            "type": "object",
            "properties": {"service_name": {"type": "string"}},
            "required": ["service_name"],
        },
    },
    {
        "name": "query_changelog",
        "description": "Fetch the recent PR and deployment changelog for the changed service.",
        "inputSchema": {
            "type": "object",
            "properties": {"service_name": {"type": "string"}},
            "required": [],
        },
    },
    {
        "name": "query_monitoring",
        "description": "Fetch a live monitoring snapshot for a service: latency, error rate, and dependency health.",
        "inputSchema": {
            "type": "object",
            "properties": {"service_name": {"type": "string"}},
            "required": ["service_name"],
        },
    },
    {
        "name": "submit",
        "description": "Submit the final list of affected services. Ends the episode and returns an F-beta(β=2) score against the ground truth.",
        "inputSchema": {
            "type": "object",
            "properties": {
                "affected_services": {
                    "type": "array",
                    "items": {"type": "string"},
                    "description": "All service names you believe are affected by the incident.",
                }
            },
            "required": ["affected_services"],
        },
    },
    {
        "name": "submit_hypothesis",
        "description": "Submit a hypothesis for partial scoring without ending the episode. Returns a delayed_reward (partial F-beta) so the agent can adjust its strategy.",
        "inputSchema": {
            "type": "object",
            "properties": {
                "affected_services": {
                    "type": "array",
                    "items": {"type": "string"},
                    "description": "Services you currently believe are affected.",
                },
                "confidence": {
                    "type": "number",
                    "description": "Your confidence in this hypothesis (0.0-1.0).",
                },
            },
            "required": ["affected_services"],
        },
    },
    {
        "name": "query_topology_diff",
        "description": "Show all topology changes (mutations) that occurred during this episode. FREE action — no budget cost.",
        "inputSchema": {
            "type": "object",
            "properties": {},
        },
    },
    {
        "name": "query_service_health",
        "description": "Get health summary for a service: tier, team, degree, investigation status. FREE action — no budget cost.",
        "inputSchema": {
            "type": "object",
            "properties": {
                "service_name": {
                    "type": "string",
                    "description": "The service to get health info for.",
                },
            },
            "required": ["service_name"],
        },
    },
]


@app.get("/mcp")
async def mcp_manifest():
    """MCP tools manifest — lists all available environment tools."""
    return {
        "schema_version": "2024-11-05",
        "name": "service_impact_env",
        "version": "2.0.0",
        "description": (
            "Cross-service impact analysis environment. Agents identify downstream "
            "services affected by a microservice change using LLM-simulated SRE tool output."
        ),
        "tools": _MCP_TOOLS,
        "execution": "Use the WebSocket at /ws for stateful episode execution.",
    }


@app.post("/mcp")
async def mcp_rpc(request: Request):
    """JSON-RPC 2.0 endpoint for MCP protocol compliance.

    Supports:
      tools/list  → returns full tools manifest
      tools/call  → returns tool schema (actual execution via WebSocket)
    """
    try:
        body   = await request.json()
        method = body.get("method", "")
        req_id = body.get("id", 1)

        if method == "initialize":
            return JSONResponse({
                "jsonrpc": "2.0", "id": req_id,
                "result": {
                    "protocolVersion": "2024-11-05",
                    "capabilities": {"tools": {}},
                    "serverInfo": {"name": "service_impact_env", "version": "0.2.0"},
                },
            })

        if method == "tools/list":
            return JSONResponse({
                "jsonrpc": "2.0", "id": req_id,
                "result": {"tools": _MCP_TOOLS},
            })

        if method == "tools/call":
            params    = body.get("params", {})
            tool_name = params.get("name", "")
            tool = next((t for t in _MCP_TOOLS if t["name"] == tool_name), None)
            if tool is None:
                return JSONResponse({
                    "jsonrpc": "2.0", "id": req_id,
                    "error": {"code": -32601, "message": f"Tool not found: {tool_name}"},
                })

            # ── Execute the tool against a real environment instance ──
            arguments = params.get("arguments", {})
            env = ServiceImpactEnvironment()

            # Auto-reset if no episode is active (MCP callers may not reset first)
            if not env._changed_service:
                seed = arguments.pop("seed", 42)
                env.reset(seed=seed)

            # Build action from MCP arguments
            action_data = {"action_type": tool_name, **arguments}
            try:
                action = ServiceImpactAction(**action_data)
            except Exception as exc:
                return JSONResponse({
                    "jsonrpc": "2.0", "id": req_id,
                    "error": {"code": -32602, "message": f"Invalid params: {exc}"},
                })

            obs = env.step(action)
            return JSONResponse({
                "jsonrpc": "2.0", "id": req_id,
                "result": {
                    "content": [
                        {"type": "text", "text": obs.message},
                    ],
                    "isError": False,
                },
            })

        return JSONResponse({
            "jsonrpc": "2.0", "id": req_id,
            "error": {"code": -32601, "message": f"Method not found: {method}"},
        })

    except Exception as exc:
        return JSONResponse(
            {"jsonrpc": "2.0", "id": None, "error": {"code": -32700, "message": str(exc)}},
            status_code=400,
        )


def main() -> None:
    """Entry point for `uv run --project . server`."""
    import uvicorn
    uvicorn.run(app, host="0.0.0.0", port=8000, log_level="info")


if __name__ == "__main__":
    main()
