"""
server/service_impact_environment.py
--------------------------------------
Core environment logic for service_impact_env.

LLM Simulator Architecture (Option A):
  - Ground truth (networkx) is NEVER exposed in result[] during queries.
  - Agents see only LLM-generated SRE tool output in observation.message.
  - result[] is populated ONLY on submit (reveals ground truth for postmortem).
  - Llama-3.1-8B via Cerebras (HF Inference Providers) generates realistic,
    noisy PagerDuty alerts, registry lookups, runbooks, and monitoring output.
  - Graceful degradation: if HF_TOKEN absent → template string fallback.

Episode lifecycle:
  1. reset(seed) → build seed-perturbed graph, pick scenario, generate incident
  2. step(query) → return LLM-generated registry/runbook/monitoring (result=[])
  3. step(submit) → score F-beta(β=2) vs ground truth, reveal correct in result[]

Reward design:
  - query step (new svc)   : +0.05
  - query step (re-query)  : -0.05
  - free action (runbook…) : None
  - budget exhaustion      : -0.4  (penalizes not submitting)
  - submit                 : F-beta(β=2) ∈ [0.0, 1.0] minus overclaiming penalty
"""
from __future__ import annotations

import os
import random
from typing import Any, List, Optional, Set
from uuid import uuid4

# OpenEnv base ---------------------------------------------------------------
try:
    from openenv.core.env_server.interfaces import Environment
except ImportError:
    from abc import ABC, abstractmethod
    class Environment(ABC):  # type: ignore[no-redef]
        def _reset_rubric(self): pass
        @abstractmethod
        def reset(self, seed=None, episode_id=None, **kwargs): ...
        @abstractmethod
        def step(self, action, timeout_s=None, **kwargs): ...
        @property
        @abstractmethod
        def state(self): ...

# Dual-import for in-repo vs Docker ------------------------------------------
try:
    from ..models import ServiceImpactAction, ServiceImpactObservation, ServiceImpactState
except ImportError:
    from models import ServiceImpactAction, ServiceImpactObservation, ServiceImpactState  # type: ignore

try:
    from .graph_builder import (
        build_service_graph,
        get_affected_services,
        get_direct_dependents,
        get_direct_dependencies,
        get_all_services,
        get_scenario,
        SERVICE_METADATA,
    )
except ImportError:
    from server.graph_builder import (  # type: ignore
        build_service_graph,
        get_affected_services,
        get_direct_dependents,
        get_direct_dependencies,
        get_all_services,
        get_scenario,
        SERVICE_METADATA,
    )

try:
    from .llm_simulator import LLMSimulator, SimulatorCache
except ImportError:
    from server.llm_simulator import LLMSimulator, SimulatorCache  # type: ignore

import networkx as nx


class ServiceImpactEnvironment(
    Environment  # type: ignore[misc]
):
    """Cross-service impact analysis environment with LLM-simulated observations.

    Agents observe realistic, noisy SRE tool output generated by Llama-3.1-8B
    (PagerDuty alerts, service registry responses, runbooks, monitoring data).
    Scoring is always against the deterministic networkx ground truth graph.

    Key properties:
    - 10,000+ unique episodes via seed-perturbed graph topology
    - Option A: agents must reason from noisy text — result[] is always [] during queries
    - F-beta (β=2) reward: recall weighted 4× over precision (SRE cost model)
    - Overclaiming penalty for submitting > 60% of all services
    - Free actions: query_runbook, query_changelog, query_monitoring (no budget cost)
    """

    SUPPORTS_CONCURRENT_SESSIONS = True

    name:        str = "service_impact_env"
    description: str = (
        "Cross-service impact analysis environment. "
        "Agents identify downstream services affected by a microservice change. "
        "Observations are LLM-generated noisy SRE tool output (Llama-3.1-8B). "
        "Reward = F-beta(β=2) of predicted vs ground-truth affected set."
    )
    version: str = "0.2.0"
    author:  str = "Rajkamal2819"

    def get_metadata(self):
        """Return environment metadata for the /metadata endpoint."""
        try:
            from openenv.core.env_server.types import EnvironmentMetadata
        except ImportError:
            from openenv.core.env_server.interfaces import EnvironmentMetadata  # type: ignore
        return EnvironmentMetadata(
            name=self.name,
            version=self.version,
            description=(
                "cascade-mind simulates an SRE incident-response workflow. "
                "An agent investigates a production change in one microservice and must "
                "identify every downstream service that could be affected \u2014 using realistic, "
                "LLM-generated tool outputs (alerts, service registry, runbooks, monitoring). "
                "Observations are generated by Llama-3.1-8B via Cerebras. "
                "Scored with F-beta(\u03b2=2) against the ground-truth networkx dependency graph."
            ),
            author=self.author,
            documentation_url="https://huggingface.co/spaces/Rajkamal2819/cascade-mind",
        )

    def __init__(self) -> None:
        super().__init__()

        # LLM simulator (optional — graceful fallback if HF_TOKEN not set)
        llm_enabled = os.environ.get("LLM_SIMULATOR_ENABLED", "true").lower() == "true"
        cache_path  = os.environ.get("LLM_CACHE_PATH", "/tmp/llm_sim_cache.json")
        self._simulator = LLMSimulator(
            hf_token=os.environ.get("HF_TOKEN", ""),
            cache=SimulatorCache(cache_path=cache_path),
            enabled=llm_enabled,
        )

        # Per-episode mutable state (initialised by reset())
        self._graph:            nx.DiGraph  = nx.DiGraph()
        self._all_services:     List[str]   = []
        self._changed_service:  str         = ""
        self._correct_affected: Set[str]    = set()
        self._queries_used:     int         = 0
        self._max_queries:      int         = 15
        self._task_difficulty:  str         = "easy"
        self._queried_services: Set[str]    = set()
        self._episode_ended:    bool        = False
        self._current_seed:     int         = 0
        self._incident_context              = None
        self._state = ServiceImpactState()

    # ── OpenEnv required interface ────────────────────────────────────────

    def reset(
        self,
        seed:       Optional[int] = None,
        episode_id: Optional[str] = None,
        **kwargs:   Any,
    ) -> ServiceImpactObservation:
        """Start a new episode.

        Each seed produces a unique graph topology + changed_service selection.
        seed % 3 determines difficulty (0=easy, 1=medium, 2=hard).
        """
        self._reset_rubric()

        if seed is None:
            seed = random.randint(0, 100_000)
        self._current_seed = seed

        # Build episode-specific perturbed graph
        self._graph       = build_service_graph(seed=seed)
        self._all_services = get_all_services(self._graph)

        # Select scenario dynamically from seed + graph
        scenario               = get_scenario(self._graph, seed)
        self._task_difficulty  = scenario["difficulty"]
        self._changed_service  = scenario["changed_service"]
        self._max_queries      = scenario["max_queries"]
        self._correct_affected = get_affected_services(self._graph, self._changed_service)

        # Reset tracking
        self._queries_used    = 0
        self._queried_services = set()
        self._episode_ended   = False
        self._incident_context = None

        self._state = ServiceImpactState(
            episode_id=episode_id or str(uuid4()),
            step_count=0,
            changed_service=self._changed_service,
            queries_used=0,
            max_queries=self._max_queries,
            correct_affected=[],   # hidden until episode ends
            predicted_affected=[],
            task_difficulty=self._task_difficulty,
            episode_ended=False,
        )

        # Generate LLM incident context (cached per seed — fast on cache hit)
        meta = SERVICE_METADATA.get(self._changed_service, {})
        incident_block = ""
        if self._simulator.is_active:
            try:
                self._incident_context = self._simulator.generate_incident_context(
                    seed=seed,
                    changed_service=self._changed_service,
                    team=meta.get("team", "platform"),
                    language=meta.get("language", "python"),
                    tier=meta.get("tier", 2),
                    difficulty=self._task_difficulty,
                )
                incident_block = (
                    f"\n\n{'═'*52}\n"
                    f"INCIDENT ALERT\n{self._incident_context.alert_text}\n\n"
                    f"CHANGE LOG\n{self._incident_context.changelog_text}\n"
                    f"{'═'*52}\n"
                )
            except Exception:
                pass   # graceful degradation — episode continues without LLM context

        n_total = len(self._all_services)
        return ServiceImpactObservation(
            changed_service=self._changed_service,
            result=[],
            queries_remaining=self._max_queries,
            message=(
                f"[{self._task_difficulty.upper()} TASK] "
                f"Service '{self._changed_service}' has a breaking change. "
                f"Identify ALL downstream services that will be affected."
                f"{incident_block}"
                f"System has {n_total} total services. "
                f"Query budget: {self._max_queries}.\n"
                f"Hint: {scenario['hint']}\n"
                f"Budget actions: query_dependents, query_dependencies. "
                f"Free actions: query_runbook, query_changelog, query_monitoring. "
                f"Finish with: submit."
            ),
            done=False,
            reward=None,
        )

    def step(
        self,
        action:    ServiceImpactAction,
        timeout_s: Optional[float] = None,
        **kwargs:  Any,
    ) -> ServiceImpactObservation:
        """Execute one action and return the resulting observation.

        Reward semantics:
          - Registry query (new service) : +0.05  — intermediate exploration signal
          - Registry query (re-query)    : -0.05  — intermediate penalty signal
          - Free action (runbook…)       : None   — no reward signal
          - Budget exhaustion            : -0.4   — terminal, episode ends
          - submit                       : F-beta(β=2) in [0.0, 1.0]  ← **evaluation metric**

        Note: step rewards (+0.05 / -0.05) are pedagogical signals only and are NOT
        summed into the terminal score. The reward returned on the 'submit' action
        is the definitive F-beta(β=2) score used for evaluation and leaderboard ranking.
        """
        self._state.step_count += 1

        # Guard: reset() not called yet
        if not self._changed_service:
            return ServiceImpactObservation(
                changed_service="",
                result=[],
                queries_remaining=0,
                message="No active episode. Call reset() to start a new episode.",
                done=False,
                reward=None,
            )

        # Guard: episode already over
        if self._episode_ended:
            return ServiceImpactObservation(
                changed_service=self._changed_service,
                result=[],
                queries_remaining=0,
                message="Episode has already ended. Call reset() to start a new episode.",
                done=True,
                reward=None,
            )

        # ── SUBMIT ────────────────────────────────────────────────────────
        if action.action_type == "submit":
            return self._handle_submit(action)

        # ── FREE ACTIONS (no budget deduction) ────────────────────────────
        if action.action_type in ("query_runbook", "query_changelog", "query_monitoring"):
            return self._handle_free_action(action)

        # ── BUDGET GUARD ──────────────────────────────────────────────────
        if self._queries_used >= self._max_queries:
            self._episode_ended    = True
            self._state.episode_ended = True
            return ServiceImpactObservation(
                changed_service=self._changed_service,
                result=[],
                queries_remaining=0,
                message=(
                    "Query budget exhausted without a submission. "
                    "Episode ended — reward = -0.4. "
                    "Submit before your budget runs out next time."
                ),
                done=True,
                reward=-0.4,
            )

        # ── VALIDATE SERVICE NAME ─────────────────────────────────────────
        svc = action.service_name
        if not svc or svc not in self._graph:
            sample = self._all_services[:6]
            return ServiceImpactObservation(
                changed_service=self._changed_service,
                result=[],
                queries_remaining=self._max_queries - self._queries_used,
                message=(
                    f"Unknown service '{svc}'. "
                    f"Valid services include: {sample}. "
                    f"No query consumed."
                ),
                done=False,
                reward=None,
            )

        # ── DETERMINE STEP REWARD ─────────────────────────────────────────
        is_requery   = svc in self._queried_services
        step_reward  = -0.05 if is_requery else 0.05

        # Execute ground-truth query (internal only — never returned to agent)
        if action.action_type == "query_dependents":
            true_result   = get_direct_dependents(self._graph, svc)
            direction_lbl = f"direct callers of '{svc}'"
        else:  # query_dependencies
            true_result   = get_direct_dependencies(self._graph, svc)
            direction_lbl = f"direct dependencies of '{svc}'"

        # Deduct budget
        self._queries_used            += 1
        self._state.queries_used       = self._queries_used
        queries_remaining              = self._max_queries - self._queries_used
        self._queried_services.add(svc)

        # Generate LLM-simulated registry response (Option A: agent sees only this)
        meta     = SERVICE_METADATA.get(svc, {})
        llm_text = self._get_registry_response(action.action_type, svc, true_result, meta)

        # Auto-terminate on budget exhaustion
        done = queries_remaining == 0
        if done:
            self._episode_ended       = True
            self._state.episode_ended = True

        penalty_note = " [⚠️ Re-query penalty: -0.05]" if is_requery else ""
        budget_note  = (
            "\n[Budget exhausted — episode ends. Submit earlier next time.]"
            if done else ""
        )

        return ServiceImpactObservation(
            changed_service=self._changed_service,
            result=[],          # Option A: never expose graph structure during queries
            queries_remaining=queries_remaining,
            message=(
                f"[{action.action_type.upper()}] {direction_lbl}\n"
                f"{llm_text}"
                f"{penalty_note}"
                f"\nQueries remaining: {queries_remaining}{budget_note}"
            ),
            done=done,
            reward=-0.4 if done else step_reward,
        )

    @property
    def state(self) -> ServiceImpactState:
        return self._state

    # ── Private helpers ───────────────────────────────────────────────────

    def _handle_free_action(
        self, action: ServiceImpactAction
    ) -> ServiceImpactObservation:
        """Handle free actions: query_runbook, query_changelog, query_monitoring."""
        svc  = action.service_name or self._changed_service
        meta = SERVICE_METADATA.get(svc, {})

        try:
            if action.action_type == "query_runbook":
                dependents   = get_direct_dependents(self._graph, svc)
                dependencies = get_direct_dependencies(self._graph, svc)
                content = self._simulator.generate_runbook(
                    seed=self._current_seed, service_name=svc,
                    dependents=dependents, dependencies=dependencies,
                    team=meta.get("team", "platform"), tier=meta.get("tier", 2),
                    difficulty=self._task_difficulty,
                )
                label = "RUNBOOK"

            elif action.action_type == "query_changelog":
                # Changelog is always about the episode's changed_service
                svc_for_change = self._changed_service
                meta_c = SERVICE_METADATA.get(svc_for_change, {})
                content = self._simulator.generate_changelog(
                    seed=self._current_seed,
                    changed_service=svc_for_change,
                    team=meta_c.get("team", "platform"),
                    difficulty=self._task_difficulty,
                )
                svc   = svc_for_change
                label = "CHANGELOG"

            else:  # query_monitoring
                dependents   = get_direct_dependents(self._graph, svc)
                dependencies = get_direct_dependencies(self._graph, svc)
                content = self._simulator.generate_monitoring(
                    seed=self._current_seed, service_name=svc,
                    dependents=dependents, dependencies=dependencies,
                    difficulty=self._task_difficulty,
                )
                label = "MONITORING"

        except Exception as exc:
            content = f"[{action.action_type} unavailable: {exc}]"
            label   = action.action_type.upper()

        return ServiceImpactObservation(
            changed_service=self._changed_service,
            result=[],
            queries_remaining=self._max_queries - self._queries_used,
            message=(
                f"[{label}] {svc}\n"
                f"{content}\n"
                f"Queries remaining: {self._max_queries - self._queries_used} "
                f"(free action — budget unchanged)"
            ),
            done=False,
            reward=None,
        )

    def _handle_submit(
        self, action: ServiceImpactAction
    ) -> ServiceImpactObservation:
        """Score the agent's prediction with F-beta (β=2) and end the episode."""
        self._episode_ended       = True
        self._state.episode_ended = True

        predicted = set(action.affected_services or [])
        correct   = self._correct_affected

        # F-beta (β=2): recall weighted 4× over precision
        # Aligns with SRE cost model — missing an affected service causes an outage
        tp = len(predicted & correct)
        fp = len(predicted - correct)
        fn = len(correct   - predicted)

        precision = tp / (tp + fp) if (tp + fp) > 0 else 0.0
        recall    = tp / (tp + fn) if (tp + fn) > 0 else 0.0
        beta      = 2.0
        fbeta     = (
            (1 + beta ** 2) * precision * recall / (beta ** 2 * precision + recall)
            if (beta ** 2 * precision + recall) > 0
            else 0.0
        )

        # Overclaiming penalty: penalise submitting > 60% of all services
        n_total    = len(self._all_services)
        n_pred     = len(predicted)
        if n_total > 0 and n_pred / n_total > 0.6:
            oversubmit_frac = min(1.0, (n_pred / n_total - 0.6) / 0.4)
            fbeta = max(0.0, fbeta - 0.3 * oversubmit_frac)

        # Clamp to open interval (0, 1) — the Phase-2 validator rejects
        # scores that are exactly 0.0 or 1.0.
        reward = round(max(0.001, min(0.999, fbeta)), 4)

        self._state.predicted_affected = sorted(predicted)
        self._state.correct_affected   = sorted(correct)   # reveal ground truth

        missed          = sorted(correct   - predicted)
        false_positives = sorted(predicted - correct)

        return ServiceImpactObservation(
            changed_service=self._changed_service,
            result=sorted(correct),           # ground truth revealed on submit
            queries_remaining=self._max_queries - self._queries_used,
            message=(
                f"Episode complete! "
                f"F-beta(β=2)={reward:.3f} | Precision={precision:.3f} | "
                f"Recall={recall:.3f} | TP={tp} FP={fp} FN={fn} | "
                f"Queries used: {self._queries_used}/{self._max_queries} | "
                f"Ground truth ({len(correct)} services): {sorted(correct)} | "
                f"Missed: {missed} | False positives: {false_positives}"
            ),
            done=True,
            reward=reward,
        )

    def _get_registry_response(
        self, action_type: str, svc: str, true_result: List[str], meta: dict
    ) -> str:
        """Get LLM-simulated registry response with graceful fallback."""
        direction = "dependents" if action_type == "query_dependents" else "dependencies"
        try:
            return self._simulator.simulate_registry_query(
                seed=self._current_seed,
                action_type=action_type,
                service_name=svc,
                true_result=true_result,
                all_services=self._all_services,
                team=meta.get("team", "platform"),
                tier=meta.get("tier", 2),
                difficulty=self._task_difficulty,
            )
        except Exception:
            return self._simulator.fallback_registry(
                svc, true_result, direction, self._task_difficulty
            )
